const initialState = {
  startedQuiz: false,
  finishedQuiz: false,
  quizPosition: 0,
  questions: [
    {id: 1, text: "Is anyone chasing you for money?", statement: "Someone is chasing you for money", category: "Money", linkId: 1},
    {id: 2, text: "Do you have payments due or unpaid accounts? E.g. phone / Work and Income / Cash converters / power bills / car loan / gyms", statement: "You have payments due or unpaid accounts", category: "Money", linkId: 1},
    {id: 3, text: "Have you recently had any problems with a product or item you’ve bought?", statement: "You have a problem with a product you’ve bought", category: "Money", linkId: 2},
    {id: 4, text: "Have you recently had any problems with a service you’ve bought?", statement: "You have had a problem with a service you’ve bought", category: "Money", linkId: 2},
    {id: 5, text: "Do you have any unpaid fines?", statement: "You have unpaid fines", category: "Money", linkId: 3},
    {id: 6, text: "Have you recently received an eviction notice?", statement: "You have recently been given an eviction notice", category: 'Housing', linkId: 4},
    {id: 7, text: "Was your tenancy bond lodged and/or returned?", statement: "Your bond has not been lodged or returned", category: 'Housing', linkId: 5},
    {id: 8, text: "Have you been able to pick up all your belongings?", statement: "You have not been able to pick up all your belongings", category: 'Housing', linkId: 4},
    {id: 9, text: "Do you have any unpaid rent?", statement: "You have unpaid rent", category: 'Housing', linkId: 4},
    {id: 10, text: "Do you have any problems with your landlord or flatmates?", statement: "You have problems with your landlord or flatmates", category: 'Housing', linkId: 4},
    {id: 11, text: "Do you have any problems with your neighbours?", statement: "You have problems with your neighbours", category: 'Housing', linkId: 6},
    {id: 12, text: "Are you or do you want to apply for government or community housing?", statement: "You would like to apply for government or community housing", category: 'Housing', linkId: 7},
    {id: 13, text: "Do you have a Notice to Appear, or are you due in Court?", statement: "You have a Notice to Appear, or are due in Court", category: 'Court', linkId: 8},
    {id: 14, text: "Have you or a family member had contact with the police you would like to discuss?", statement: "You’d like to discuss contact you or a family member has had with the police", category: 'Court', linkId: 8},
    {id: 15, text: "Are you receiving the appropriate Work and Income benefits?", statement: "You are having problems with Work and Income", category: 'Work and Income', linkId: 9},
    {id: 16, text: "Would you like to change or review any of these arrangements?", statement: "You would like to review or change your Work and Income benefits", category: 'Work and Income', linkId: 9},
    {id: 17, text: "The safety of yourself or your children?", statement: "You have concerns about the safety of yourself and or your children", category: 'Relationships', preface: "Would you like to discuss ...", linkId: 10},
    {id: 18, text: "Arrangements, plans or orders about children? (e.g. who the child/ren live with, spend time with, or your involvement in major long-term issues)", statement: "You would like to discuss arrangements, plans or orders about children in your life", category: 'Relationships', preface: "Would you like to discuss ...", linkId: 11},
    {id: 19, text: "Any concerns about Child Youth and Family and your whānau?", statement: "You have concerns about  CYFS (Oranga Tamariki) and your whānau", category: 'Relationships', preface: "Would you like to discuss ...", linkId: 12},
    {id: 20, text: "Your rights in any personal relationship, including divorce or separation?", statement: "You want to know about your rights in any personal relationship, including divorce or separation", category: 'Relationships', preface: "Would you like to discuss ...", linkId: 13},
    {id: 21, text: "Concerns about your experiences as a child, while you were in the care of adults or institutions?", statement: "You have concerns about your experiences as a child, while you were in the care of adults or institutions", category: 'Relationships', preface: "Would you like to discuss ...", linkId: 14},
    {id: 22, text: "Are you having any problems at work?", statement: "You are having problems at work", category: 'Employment', linkId: 14},
    {id: 23, text: "Are you worried about getting fired, laid off, or having your hours cut?", statement: "You are worried about losing your job or having your hours cut", category: 'Employment', linkId: 14},
    {id: 24, text: "Does your employer owe you money?", statement: "Your employee owes you money", category: 'Employment', linkId: 14},
    {id: 25, text: "Do you feel like you have been treated unfairly due to your gender, ethnicity, religion etc.?", statement: "You are being discriminated against", category: 'Employment'},
    {id: 26, text: "Do you have concerns around your immigration status in New Zealand?", statement: "You have concerns about your immigration status in NZ", category: 'Other'},
    {id: 27, text: "Are you having trouble bringing family members to New Zealand?", statement: "You are having trouble bringing family members to NZ", category: 'Other'},
    {id: 28, text: "Are you worried about how your child is being treated at school?", statement: "You are worried about how your child is being treated at school", category: 'Other', linkId: 15}
    ],
  results: [],
  links: [
      {linkId: 1, title: "Credit and debt", url: "http://communitylaw.org.nz/community-law-manual/chapter-13-credit-and-debt/what-this-chapter-covers-chapter-13/"},
      {linkId: 2, title: "Consumer protection", url: "http://communitylaw.org.nz/community-law-manual/chapter-12-consumer-protection/what-this-chapter-covers-chapter-12/"},
      {linkId: 3, title: "Court fines", url: "http://communitylaw.org.nz/community-law-manual/chapter-32-court-fines/what-this-chapter-covers-chapter-32/"},
      {linkId: 4, title: "Tenancy and housing", url: "http://communitylaw.org.nz/community-law-manual/chapter-15-tenancy-and-housing/what-this-chapter-covers-chapter-15/"},
      {linkId: 5, title: "Bond and tenancy", url: "https://www.tenancy.govt.nz/about-tenancy-services/contact-us/"},
      {linkId: 6, title: "Neighbours", url: "http://communitylaw.org.nz/community-law-manual/chapter-11-neighbourhood-life/what-this-chapter-covers-chapter-11/"},
      {linkId: 7, title: "Community and government housing", url: "http://communitylaw.org.nz/community-law-manual/chapter-15-tenancy-and-housing/social-housing-tenants-in-state-and-community-housing-chapter-15/"},
      {linkId: 8, title: "Criminal law", url: "http://communitylaw.org.nz/community-law-manual/chapter-34-the-criminal-courts/what-this-chapter-covers-chapter-34/"},
      {linkId: 9, title: "Dealing with Work and Income", url: "http://communitylaw.org.nz/community-law-manual/chapter-7-dealing-with-work-and-income/what-this-chapter-covers-chapter-7/"},
      {linkId: 10, title: "Domestic violence", url: "http://communitylaw.org.nz/community-law-manual/chapter-29-domestic-violence/what-this-chapter-covers-chapter-29/"},
      {linkId: 11, title: "Parents, guardians and caregivers", url: "http://communitylaw.org.nz/community-law-manual/chapter-27-parents-guardians-and-caregivers/what-this-chapter-covers-chapter-27/"},
      {linkId: 12, title: "Child Youth and Family", url: "http://communitylaw.org.nz/community-law-manual/chapter-28-dealing-with-child-youth-and-family/what-this-chapter-covers-chapter-28/"},
      {linkId: 13, title: "Personal relationships and the law", url: "http://communitylaw.org.nz/community-law-manual/chapter-26-adult-relationships/what-this-chapter-covers-chapter-26/"},
      {linkId: 14, title: "Resolving employment problems", url: "http://communitylaw.org.nz/community-law-manual/chapter-18-resolving-employment-problems/what-this-chapter-covers-chapter-18/"},
      {linkId: 15, title: "Student rights", url: "http://www.wclc.org.nz/student-rights-service/"}
  ]
}

export default initialState
